const dummyProducts = [
  {
    name: "Titan Raga",
    description: "Elegant analog watch designed for everyday elegance.",
    brand: "Titan",
    category: "Women",
    price: 899,
    discountedPrice: 749,
    images: ["https://placehold.co/600x600/f5e6e0/7a4a3a/png?text=Titan+Raga"],
    color: "rose gold",
    material: "stainless steel",
    strapType: "Chain Strap",
    waterResistance: "20m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "Out of Stock",
  },
  {
    name: "Casio Vintage A168",
    description: "Retro digital watch with backlight, alarm and stopwatch.",
    brand: "Casio",
    category: "Men",
    price: 3495,
    discountedPrice: 2999,
    images: ["https://placehold.co/600x600/e2e8f0/334155/png?text=Casio+Vintage+A168"],
    color: "silver",
    material: "stainless steel",
    strapType: "Metal Bracelet",
    waterResistance: "30m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Fastrack Reflex Vox",
    description: "Sporty smart band with heart rate and step tracking.",
    brand: "Fastrack",
    category: "Kids",
    price: 1995,
    discountedPrice: 1499,
    images: ["https://placehold.co/600x600/dbeafe/1e3a8a/png?text=Fastrack+Reflex+Vox"],
    color: "black",
    material: "silicone",
    strapType: "Silicone Strap",
    waterResistance: "50m",
    warranty: "1 Year",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Fossil Grant Chronograph",
    description: "Classic chronograph with a textured dial and leather strap.",
    brand: "Fossil",
    category: "Men",
    price: 12995,
    discountedPrice: 9499,
    images: ["https://placehold.co/600x600/fef3c7/78350f/png?text=Fossil+Grant"],
    color: "brown",
    material: "leather",
    strapType: "Leather Strap",
    waterResistance: "50m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "Out of Stock",
  },
  {
    name: "Sonata Sitara",
    description: "Slim ladies' watch with a mother-of-pearl dial.",
    brand: "Sonata",
    category: "Women",
    price: 1295,
    discountedPrice: 1099,
    images: ["https://placehold.co/600x600/fce7f3/831843/png?text=Sonata+Sitara"],
    color: "gold",
    material: "brass",
    strapType: "Chain Strap",
    waterResistance: "30m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "In Stock",
  },
  {
    name: "Seiko 5 Sports Automatic",
    description: "Self-winding automatic with day-date display and exhibition caseback.",
    brand: "Seiko",
    category: "Men",
    price: 24500,
    discountedPrice: 21999,
    images: ["https://placehold.co/600x600/d1fae5/064e3b/png?text=Seiko+5+Sports"],
    color: "green",
    material: "stainless steel",
    strapType: "Metal Bracelet",
    waterResistance: "100m",
    warranty: "3 Years",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Timex Weekender",
    description: "Lightweight everyday watch with an Indiglo night light.",
    brand: "Timex",
    category: "Men",
    price: 3999,
    discountedPrice: 3299,
    images: ["https://placehold.co/600x600/e7e5e4/44403c/png?text=Timex+Weekender"],
    color: "khaki",
    material: "brass",
    strapType: "Nylon Strap",
    waterResistance: "30m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "Out of Stock",
  },
  {
    name: "Noise ColorFit Pulse 3",
    description: "Bright AMOLED smartwatch with Bluetooth calling.",
    brand: "Noise",
    category: "Kids",
    price: 5999,
    discountedPrice: 2499,
    images: ["https://placehold.co/600x600/ede9fe/4c1d95/png?text=Noise+ColorFit+Pulse+3"],
    color: "jet black",
    material: "polycarbonate",
    strapType: "Silicone Strap",
    waterResistance: "IP68",
    warranty: "1 Year",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Daniel Wellington Classic Petite",
    description: "Minimalist dial with a mesh strap, sized for slimmer wrists.",
    brand: "Daniel Wellington",
    category: "Women",
    price: 11900,
    discountedPrice: 9520,
    images: ["https://placehold.co/600x600/fff1f2/9f1239/png?text=DW+Classic+Petite"],
    color: "rose gold",
    material: "stainless steel",
    strapType: "Mesh Strap",
    waterResistance: "30m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "Out of Stock",
  },
  {
    name: "Casio Baby-G BGD-565",
    description: "Shock-resistant digital watch in bright, playful colours.",
    brand: "Casio",
    category: "Kids",
    price: 8995,
    discountedPrice: 7495,
    images: ["https://placehold.co/600x600/cffafe/155e75/png?text=Casio+Baby-G"],
    color: "teal",
    material: "resin",
    strapType: "Resin Strap",
    waterResistance: "100m",
    warranty: "2 Years",
    isFeatured: false,
    isAvailable: "In Stock",
  },
  {
    name: "Tissot PRX Powermatic 80",
    description: "70s-inspired automatic with an integrated bracelet and 80-hour reserve.",
    brand: "Tissot",
    category: "Men",
    price: 59500,
    discountedPrice: 54900,
    images: ["https://placehold.co/600x600/dbeafe/172554/png?text=Tissot+PRX"],
    color: "blue",
    material: "stainless steel",
    strapType: "Metal Bracelet",
    waterResistance: "100m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "Out of Stock",
  },
  {
    name: "Sonata Kids Cartoon",
    description: "Colourful analog watch with easy-to-read numerals for children.",
    brand: "Sonata",
    category: "Kids",
    price: 699,
    discountedPrice: 549,
    images: ["https://placehold.co/600x600/fef9c3/854d0e/png?text=Sonata+Kids"],
    color: "yellow",
    material: "plastic",
    strapType: "Silicone Strap",
    waterResistance: "10m",
    warranty: "6 Months",
    isFeatured: false,
    isAvailable: "In Stock",
  },
];

export default dummyProducts;