const dummyProducts = [
  {
    name: "G-SHOCK",
    description: "Rugged digital watch built for extreme durability.",
    brand: "Boat",
    category: "Women",
    price: 644,
    discountedPrice: null,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/gshock1.jpg"],
    color: "black",
    material: "stainless steel",
    strapType: "Metal Strap",
    waterResistance: "50m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "In Stock",
  },
  {
    name: "Fossil Gen 6",
    description: "Smartwatch with heart rate monitoring and GPS.",
    brand: "Fossil",
    category: "Men",
    price: 1299,
    discountedPrice: 999,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/fossil1.jpg"],
    color: "brown",
    material: "leather",
    strapType: "Leather Strap",
    waterResistance: "30m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Titan Raga",
    description: "Elegant analog watch designed for everyday elegance.",
    brand: "Titan",
    category: "Women",
    price: 899,
    discountedPrice: 749,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/titan1.jpg"],
    color: "rose gold",
    material: "stainless steel",
    strapType: "Chain Strap",
    waterResistance: "20m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "Out of Stock",
  },
  {
    name: "Apple Watch SE",
    description: "Smartwatch with fitness tracking and notifications.",
    brand: "Apple",
    category: "Kids",
    price: 2499,
    discountedPrice: 2299,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/apple1.jpg"],
    color: "midnight",
    material: "aluminum",
    strapType: "Silicone Strap",
    waterResistance: "50m",
    warranty: "1 Year",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Casio Vintage",
    description: "Retro-style digital watch with classic design.",
    brand: "Casio",
    category: "Men",
    price: 499,
    discountedPrice: null,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/casio1.jpg"],
    color: "gold",
    material: "stainless steel",
    strapType: "Metal Strap",
    waterResistance: "30m",
    warranty: "6 Months",
    isFeatured: false,
    isAvailable: "In Stock",
  },
  {
    name: "Fastrack Sport",
    description: "Durable sports watch for active lifestyles.",
    brand: "Fastrack",
    category: "Men",
    price: 1099,
    discountedPrice: 899,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/fastrack1.jpg"],
    color: "blue",
    material: "resin",
    strapType: "Silicone Strap",
    waterResistance: "100m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "In Stock",
  },
  {
    name: "Michael Kors Bradshaw",
    description: "Chronograph watch with a luxurious touch.",
    brand: "Michael Kors",
    category: "Women",
    price: 2999,
    discountedPrice: 2499,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/mk1.jpg"],
    color: "silver",
    material: "stainless steel",
    strapType: "Chain Strap",
    waterResistance: "50m",
    warranty: "2 Years",
    isFeatured: true,
    isAvailable: "In Stock",
  },
  {
    name: "Timex Weekender",
    description: "Classic canvas strap watch for casual wear.",
    brand: "Timex",
    category: "Kids",
    price: 799,
    discountedPrice: null,
    images: ["https://res.cloudinary.com/demo/image/upload/v1/timex1.jpg"],
    color: "olive",
    material: "nylon",
    strapType: "Canvas Strap",
    waterResistance: "30m",
    warranty: "1 Year",
    isFeatured: false,
    isAvailable: "In Stock",
  },
];

export default dummyProducts;